### ISSUE TITLE
make armani

### ISSUE THREAD

**Issue by ghost** [grub4android/build#6]
if i have it right this should be the build command.
# make armani

make: **\* No rule to make target 'armani'.  Stop.

can you provide a better build instruction, and also a porting guide document covering
all the bases.

I'm interested in armani because msm8226. I have two samsung devices i would like to try a build for. thanks

m

**Comment by M1cha** [comment]
this project got replaced by EFIDroid: https://github.com/efidroid/projectmanagement/wiki
Even if u want to install GRUB for booting linux and not just Android multiboot, that's still possible by using grub-efi.
